export default {
PROD_SERVER_URI: "https://coronivia-280216.wm.r.appspot.com",
DEV_SERVER_URI: "http://localhost:5000",

 ERROR_PHRASES: ['Aww snap!',
 'Trouble down at mill!',
 'Sad news friend!',
 "Wouldn't you just know it?",
 'Fiddlesticks!',
 'Poop!',
 'Bad luck friend!',
 'Nothing to see here, citizen.',
 'A very tinny result.',
 'Uh, O Spagetti-os!',
 "It's a trap!",
 "Dammit!",
 'Seriously?',
 'For the love of Pete!',
 'Since the dawn of time, mankind has experienced errors...',
 'Blammo!',
 'Son of a biscuit!',
 'Bummer dude!',
 "I just can't do it captain!",
 'Who would have thunk it?',
 "Well, I'll be go to hell.",
 'Shiiiooot!',
 'Danger Will Robinson!',
 'So say we all.',
 'By the Hammer of Grabthar!',
 'There can be only one!',
 'Doh!',
 'This is the way.'
]
}